In [ ]:
from __future__ import absolute_import, division, print_function, unicode_literals

# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt

print(tf.__version__)


In [12]:
f_x30 = open('30_single/VCS_fields_TT_x_ROM.txt', 'r')
x30 = np.loadtxt(f_x30)
print(x30.shape)
f_y30 = open('30_single/VCS_fields_TT_y_ROM.txt', 'r')
y30 = np.loadtxt(f_y30)
print(y30.shape)
f_x28 = open('28_single/VCS_fields_TT_x_ROM.txt', 'r')
x28 = np.loadtxt(f_x28)
print(x28.shape)
f_y28 = open('28_single/VCS_fields_TT_y_ROM.txt', 'r')
y28 = np.loadtxt(f_y28)
print(y28.shape)

(100000, 20)
(100000, 22)
(100000, 20)
(100000, 22)


In [13]:
dim_x = int(x30.shape[1])
dim_y = int(y30.shape[1])
print(dim_x)
print(dim_y)
#f_sample_grid_d1 = open('sample_grid_d1.txt', 'r')
#sample_grid_d1 = 2*(np.loadtxt(f_sample_grid_d1) - 0.5)
#sample_grid_d1 = np.loadtxt(f_sample_grid_d1)
#print(sample_grid_d1)
#f_sample_grid_d2 = open('sample_grid_d2.txt', 'r')
#sample_grid_d2 = 10*(np.loadtxt(f_sample_grid_d2) - 0.1)
#sample_grid_d2 = np.loadtxt(f_sample_grid_d2)
#print(sample_grid_d2)

20
22


In [20]:
# the sample_grid are the rom_coords including the parameter
# the train_values are the rom_coords at the next step
#
x30_sample_grid_tmp = np.delete(x30, (x30.shape[0]-1), axis=0)
x30_train_values = np.delete(x30, (0), axis=0)
#print(x30)
print(x30_sample_grid_tmp)
#print(x30_train_values)
x30_sample_grid = 30*np.ones((x30_sample_grid_tmp.shape[0],x30_sample_grid_tmp.shape[1]+1))

print(x30_sample_grid)



[[ 5.75274955e+03  5.41552348e+03  4.43526365e+02 ...  1.90554095e+00
  -1.99106091e+01  8.16375429e+00]
 [ 5.75165561e+03  5.41490095e+03  4.41823171e+02 ...  1.89977761e+00
  -1.99094891e+01  8.16219945e+00]
 [ 5.75056410e+03  5.41427517e+03  4.40118368e+02 ...  1.89295461e+00
  -1.99077719e+01  8.16072875e+00]
 ...
 [ 6.75353671e+03  5.34840064e+03  1.35542855e+03 ...  5.74837091e+00
  -1.96705259e+01  9.52966995e+00]
 [ 6.75172582e+03  5.34916626e+03  1.35450338e+03 ...  5.74417348e+00
  -1.96732126e+01  9.52683644e+00]
 [ 6.74991506e+03  5.34993016e+03  1.35357614e+03 ...  5.73996570e+00
  -1.96758906e+01  9.52400428e+00]]
[[30. 30. 30. ... 30. 30. 30.]
 [30. 30. 30. ... 30. 30. 30.]
 [30. 30. 30. ... 30. 30. 30.]
 ...
 [30. 30. 30. ... 30. 30. 30.]
 [30. 30. 30. ... 30. 30. 30.]
 [30. 30. 30. ... 30. 30. 30.]]


In [ ]:
#train_values = samples_optimal_clustering.reshape(110)
#train_values = np.concatenate((lcs0, lcs1, lcs2, lcs3, lcs4, lcs5, lcs6, lcs7))
#print(train_values)
#train_values = np.reshape(train_values,(lcs0.shape[0],8), order='F')
#print(train_values.shape)
#train_values = 1./train_values
#np.argmax(train_values, axis = 1)
#for i in range(0,train_values.shape[0]):
#    sum_row = np.sum(train_values[i,:])
#    train_values[i,:] = train_values[i,:] / sum_row
    #print(sum_row)
#print(train_values)
train_values = np.transpose(trainANN)
print(trainANN)
print(train_values.shape)
print(train_values.shape[1])

In [ ]:
f_sample_grid = open('sample_grid.txt', 'r')
sample_grid = np.loadtxt(f_sample_grid)
print(sample_grid.shape)
print(sample_grid)

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(512, activation='relu', input_shape=[2]),
    keras.layers.Dense(512, activation='relu'),
    keras.layers.Dense(512, activation='relu'),
    keras.layers.Dense(512, activation='relu'),
    keras.layers.Dense(512, activation='relu'),
    keras.layers.Dense(512, activation='relu'),
    keras.layers.Dense(512, activation='relu'),
    keras.layers.Dense(512, activation='relu'),
    keras.layers.Dense(512, activation='relu'),
    keras.layers.Dense(train_values.shape[1])
])

In [ ]:
model.compile(optimizer='adam',
              loss='mse',
              metrics=['mae', 'mse'])

In [ ]:
model.fit(sample_grid, train_values, epochs=10000)

In [ ]:
pred_sg = model.predict(sample_grid)
print(pred_sg.shape)

In [ ]:
np.argmax(pred_sg, axis=1)


In [ ]:
np.argmax(train_values, axis = 1)

In [ ]:
np.argmax(pred_sg, axis=1) - np.argmax(train_values, axis = 1)

In [ ]:
f_fine_sample_grid = open('fine_sample_grid.txt', 'r')
fine_sample_grid = np.loadtxt(f_fine_sample_grid)
print(fine_sample_grid.shape)
print(fine_sample_grid)

In [ ]:
pred_fsg = model.predict(fine_sample_grid)
np.set_printoptions(threshold=np.inf)
print(pred_fsg.shape)
np.savetxt('pred_fsg.txt', pred_fsg)
#np.argmax(pred_fsg, axis=1)

In [ ]:
#f_combination_optimal_c = open('combination_optimal_c.txt', 'r')
#combination_optimal_c = np.loadtxt(f_combination_optimal_c)
#print(combination_optimal_c)
#print(sample_grid.shape)
#print(train_values.shape)
#print(combination_optimal_c.shape)
#detailed_train_values = combination_optimal_c.reshape(1640)
#print(detailed_train_values.shape)

In [ ]:
#model_2 = keras.Sequential([
#    keras.layers.Dense(2, activation='relu'),
#    keras.layers.Dense(1024, activation='relu'),
#    keras.layers.Dense(1024, activation='relu'),
#    keras.layers.Dense(8, activation='softmax')
#])
#model_2.compile(optimizer='adam',
#              loss='sparse_categorical_crossentropy',
#              metrics=['accuracy'])
#model_2.fit(fine_sample_grid, detailed_train_values, epochs=500)

In [ ]:
#pred_mod2 = model_2.predict(fine_sample_grid)
#save_pred_mod2_fsg = np.argmax(pred_mod2, axis=1)
#np.savetxt('save_pred_mod2_fsg.txt', save_pred_mod2_fsg)

In [ ]:
pred_mod1 = np.argmax(pred_fsg, axis=1)
#np.savetxt('smart_save_pred_mod1_fsg.txt', pred_mod1)